- name: Instalando os pacotes necessarios.
  apt:
      name: apt-transport-https
      state: present
      update_cache: yes

- name: Adicionando grafana gpg key
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: adicionando o repositorio do grafana
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Instalando o grafana ( esperamos que nao demore muito... *_* )
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: Verificando se o grafana esta acessivel
  uri:
    url: http://localhost:3000
    method: GET
    status_code: 200
