- name: Criando grupo de usuario do prometheus 
  group: name="{{groupId}}"
  become: true

- name: Creando o usuario do prometheus
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present

- name: Instalando prometheus ( esperamos que nao demore muito... *_* )
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copiando arquivo prometheus para o bin
  copy:
    src: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
    dest: "/usr/local/bin/prometheus"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755

- name: Deletando o arquivo prometheus no /tmp
  file:
    path: '/tmp/prometheus-{{ version }}.linux-amd64'
    state: absent

- name: Criando diretorios necessarios
  file: 
    path: "/data/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Criando diretorios necessarios 
  file: 
    path: "/etc/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Arquivo de configuracao
  template:
    src: prometheus.conf.j2
    dest: /etc/prometheus/prometheus.conf

- name: Configurando prometheus como um servico no linux
  template:
    src: init.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: systemd_reload

- name: Iniciando o servico do prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Verificando se o prometheus esta acessivel
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200
